/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class i2c_U2CWrapper */

#ifndef _Included_i2c_U2CWrapper
#define _Included_i2c_U2CWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef i2c_U2CWrapper_LS_DROPPED_BY_I2C_BRIDGE
#define i2c_U2CWrapper_LS_DROPPED_BY_I2C_BRIDGE 2L
#undef i2c_U2CWrapper_LS_DROPPED_BY_SLAVE
#define i2c_U2CWrapper_LS_DROPPED_BY_SLAVE 3L
#undef i2c_U2CWrapper_LS_RAISED_BY_I2C_BRIDGE
#define i2c_U2CWrapper_LS_RAISED_BY_I2C_BRIDGE 4L
#undef i2c_U2CWrapper_LS_RELEASED
#define i2c_U2CWrapper_LS_RELEASED 1L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_10KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_10KHZ 46L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_25KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_25KHZ 16L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_2KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_2KHZ 242L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_50KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_50KHZ 6L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_5KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_5KHZ 96L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_62KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_62KHZ 4L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_71KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_71KHZ 3L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_83KHZ
#define i2c_U2CWrapper_U2C_I2C_FREQ_83KHZ 2L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_FAST
#define i2c_U2CWrapper_U2C_I2C_FREQ_FAST 0L
#undef i2c_U2CWrapper_U2C_I2C_FREQ_STD
#define i2c_U2CWrapper_U2C_I2C_FREQ_STD 1L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_100KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_100KHZ 1L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_10KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_10KHZ 46L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_200KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_200KHZ 0L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_25KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_25KHZ 16L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_2KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_2KHZ 242L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_50KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_50KHZ 6L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_5KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_5KHZ 96L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_62KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_62KHZ 4L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_71KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_71KHZ 3L
#undef i2c_U2CWrapper_U2C_SPI_FREQ_83KHZ
#define i2c_U2CWrapper_U2C_SPI_FREQ_83KHZ 2L
/* Inaccessible static: dllLoaded */
/*
 * Class:     i2c_U2CWrapper
 * Method:    closeDeviceN
 * Signature: (Li2c/U2CDevice;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_closeDeviceN
  (JNIEnv *, jclass, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getClockSynchN
 * Signature: (Li2c/U2CDevice;Li2c/WrapedInt;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_getClockSynchN
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getDeviceCountN
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_i2c_U2CWrapper_getDeviceCountN
  (JNIEnv *, jclass);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getDllVersionN
 * Signature: (Li2c/U2CVersionInfo;)V
 */
JNIEXPORT void JNICALL Java_i2c_U2CWrapper_getDllVersionN
  (JNIEnv *, jclass, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getDriverVersionN
 * Signature: (Li2c/U2CDevice;Li2c/U2CVersionInfo;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_getDriverVersionN
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getFirmwareVersionN
 * Signature: (Li2c/U2CDevice;Li2c/U2CVersionInfo;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_getFirmwareVersionN
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getI2cFreqN
 * Signature: (Li2c/U2CDevice;Li2c/WrapedInt;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_getI2cFreqN
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    getSerialNumN
 * Signature: (Li2c/U2CDevice;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_getSerialNumN
  (JNIEnv *, jclass, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    isDeviceValidN
 * Signature: (Li2c/U2CDevice;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_isDeviceValidN
  (JNIEnv *, jclass, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    openDeviceBySerialNumN
 * Signature: (JLi2c/U2CDevice;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_openDeviceBySerialNumN
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    openDeviceN
 * Signature: (ILi2c/U2CDevice;)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_openDeviceN
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     i2c_U2CWrapper
 * Method:    readN
 * Signature: (Li2c/U2CDevice;Li2c/U2CTransaction;[B)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_readN
  (JNIEnv *, jclass, jobject, jobject, jbyteArray);

/*
 * Class:     i2c_U2CWrapper
 * Method:    scanForSlavesN
 * Signature: (Li2c/U2CDevice;Li2c/U2CSlaveAdrList;[B)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_scanForSlavesN
  (JNIEnv *, jclass, jobject, jobject, jbyteArray);

/*
 * Class:     i2c_U2CWrapper
 * Method:    setClockSynchN
 * Signature: (Li2c/U2CDevice;Z)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_setClockSynchN
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     i2c_U2CWrapper
 * Method:    setI2cFreqN
 * Signature: (Li2c/U2CDevice;I)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_setI2cFreqN
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     i2c_U2CWrapper
 * Method:    writeN
 * Signature: (Li2c/U2CDevice;Li2c/U2CTransaction;[B)I
 */
JNIEXPORT jint JNICALL Java_i2c_U2CWrapper_writeN
  (JNIEnv *, jclass, jobject, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
