# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/openservointerface

FORMS += mainwin.ui \
         aboutbox.ui 
HEADERS += maintestwindow.h \
           registers.h \
           aboutclass.h 
SOURCES += main.cpp \
           maintestwindow.cpp \
           aboutclass.cpp 
TARGET = ../bin/openservointerface
CONFIG += debug \
warn_on \
qt \
thread
TEMPLATE = app
